### ISSUE TITLE
can't run on windows 7 32 bit (solved)

### ISSUE THREAD

**Issue by mouhmmad** [AztecRabbit/Brainfuck-Tunnel-Psiphon-Version#1]
can anyone tell me how to use this on my 32bit windows 7!

**Comment by aztecrabbit** [comment]
64 bit only.

**Comment by mouhmmad** [comment]
> 64 bit only.

solved by changing the " psiphon-tunnel-core.exe" 64 bit with a 32 bit in "C:\Windows\System32\brainfuck-tunnel-psiphon-version\storage\psiphon
thanks bro for this great tool.
now im asking for a way to use on android if possible.
